### ISSUE TITLE
Unaligned SAML login options

### ISSUE THREAD

**Issue by blakestoddard** [18F/uaa-customized-boshrelease#13]
Randomly spotted today that the bottom two agency login options at [https://login.fr.cloud.gov/login](https://login.fr.cloud.gov/login) are unaligned (FDIC.gov and EPA.gov) from what appears to be because of the FDIC logo size. Should be a relatively easy fix? (famous last words)

<img width="475" alt="screenshot 2017-10-11 19 46 21" src="https://user-images.githubusercontent.com/7963833/31472450-dee0a1a4-aebc-11e7-92d9-1313eccbc387.png">

**Comment by mogul** [comment]
We noticed a while back but have been dealing with other issues. Good to get a reminder because we stopped noticing it; thanks! We're limited in what we can do in these templates, but I think it should be addressable.

**Comment by mogul** [comment]
Sorted, thanks!
